language: python
python:
    - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libxml2-utils
before_script:
    - git clone --recursive --branch $VERSION https://github.com/IATI/IATI-Standard-SSOT.git
    - git clone https://github.com/IATI/IATI-Developer-Documentation.git
    - git clone https://github.com/IATI/IATI-Guidance.git
    - cd IATI-Standard-SSOT
    - pip install -r requirements.txt
    - git clone https://github.com/IATI/IATI-Websites.git
    - rm -rf $HEAD_REPO_NAME
    - git clone --branch $HEAD_BRANCH $HEAD_REPO_URL
    - cd IATI-Extra-Documentation/en
    - ln -s ../../IATI-Websites/iatistandard/_templates/ ./
    - ln -s ../../IATI-Websites/iatistandard/_static/ ./
    - cd ../..
    - mkdir docs
    - cd docs
    - git init
    - cd ..
script:
    - ./combined_gen.sh
deploy:
    project: IATI-Standard-SSOT/docs-copy/en/_build/dirhtml/
    provider: surge
    domain: $HEAD_BRANCH-$REPO_NAME-refbot.surge.sh
    skip-cleanup: true
    on:
        all_branches: true
after_script:
    - >
      curl -H "Authorization: token $GITHUB_TOKEN" --request POST $GITHUB_API_URL --data '{"body":"Okay - A demo site should have been deployed here: http://'"$HEAD_BRANCH"'-'"$REPO_NAME"'-refbot.surge.sh"}'
