language: python
python:
    - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libxml2-utils
before_script:
    - ./before_script.sh
script:
    - ./combined_gen.sh
deploy:
    project: IATI-Standard-SSOT/docs-copy/en/_build/dirhtml/
    provider: surge
    domain: $HEAD_BRANCH-$REPO_NAME-refbot.surge.sh
    skip-cleanup: true
    on:
        all_branches: true
after_deploy:
    - >
      curl -H "Authorization: token $GITHUB_TOKEN" --request POST $GITHUB_API_URL --data '{"body":"Okay - A demo site should have been deployed here: http://'"$HEAD_BRANCH"'-'"$REPO_NAME"'-refbot.surge.sh"}'
